elasticsearch-client:
  clusterName: "elasticsearch-oss"
  nodeGroup: "client"
  roles:
    master: "false"
    ingest: "false"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.10.0
  replicas: 1
  masterService: "elasticsearch-oss-master"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi
elasticsearch-master:
  clusterName: "elasticsearch-oss"
  nodeGroup: "master"
  roles:
    master: "true"
    ingest: "false"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.10.0
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 2Gi
elasticsearch-data:
  clusterName: "elasticsearch-oss"
  nodeGroup: "data"
  roles:
    master: "false"
    ingest: "false"
    data: "true"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.10.0
  masterService: "elasticsearch-oss-master"
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "1000m"
      memory: "4Gi"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
elasticsearch-ingest:
  clusterName: "elasticsearch-oss"
  nodeGroup: "ingest"
  roles:
    master: "false"
    ingest: "true"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.10.0
  masterService: "elasticsearch-oss-master"
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 2Gi
